Update Hily.json
OpenTermsArchive/dating-declarations pull request #227
Opened 2024-12-27 08:41 UTC by mvidonne

new cursor

2025-01-15 20:08 UTC, Cli4d requested changes
Hi @mvidonne,

Thank you for updating these services to restore tracking of their declarations. I have reviewed your contribution, and it looks good overall.

However, I need to request one change. There is an issue with the formatting of the JSON file, which is causing it to fail one of the required tests before we can merge your PR.

To fix this issue, please run the following command as described in [our documentation](https://docs.opentermsarchive.org/api/cli/#linting-declarations). In your case, you can execute:

`npx ota lint --fix --services Hily`

Make sure to run the `npm install` command before executing the lint fixing command.

I am requesting this change because your contribution is made via a fork that I do not have access to, so I cannot make the changes myself. If you encounter any issues while making the requested changes, please let me know, and I will find a workaround to help merge your contribution.

Thank you!

2025-01-16 06:52 UTC, MattiSG commented
@Cli4d from the metadata, it seems that it is made on a branch (`mvidonne-patch-5`) 🙂
I checked, and we had made a mistake in the permissions that prevented you from editing files in this repository. I have updated the permissions and it should thus now be possible for you to correct the lint! Sorry for that.

2025-01-17 15:19 UTC, Cli4d commented
Thanks for the clarification Matti. I'll proceed to fix the lining error and merge this PR

2025-01-17 15:25 UTC, Cli4d approved these changes

2025-01-17 15:31 UTC, Cli4d approved these changes
Hi @mvidonne,

I have fixed the linting issue that was preventing the merge. Your contribution looks great and is ready to be merged. However, we are currently experiencing a minor problem with some CI tests (unrelated to your contribution) that we are in the process of resolving. Once those issues are sorted out, I will go ahead and merge your contribution.

Thank you once again for your valuable contribution!

2025-01-21 09:21 UTC, merged