Update AdopteUnMec.json
OpenTermsArchive/dating-declarations pull request #87
Opened 2022-04-22 17:15 UTC by mvidonne

2022-04-25 07:04 UTC, MattiSG commented on declarations/AdopteUnMec.json
> +  "Imprint": {
```suggestion
    "Imprint": {
```

2022-05-17 06:58 UTC, MattiSG commented
@Amustache I suggest that you rebase this commit and use the linting feature to correct the file indentation 🙂

2022-06-20 15:48 UTC, clementbiron requested changes

2022-06-28 08:47 UTC, clementbiron approved these changes

2022-06-28 09:24 UTC, merged